# Generated by Django 6.0.1 on 2026-02-11 18:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_code', models.CharField(max_length=50, unique=True)),
                ('initial_scenario', models.CharField(blank=True, max_length=100)),
                ('terminal_node', models.CharField(blank=True, max_length=100)),
                ('risk_level', models.CharField(blank=True, max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('is_complete', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ResearchConsent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant_code', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(choices=[('consented', 'Consented'), ('declined', 'Declined'), ('withdrawn', 'Withdrawn')], default='consented', max_length=20)),
                ('consent_to_data_collection', models.BooleanField(default=False)),
                ('consent_to_longitudinal', models.BooleanField(default=False)),
                ('role', models.CharField(blank=True, max_length=50)),
                ('department_category', models.CharField(blank=True, max_length=50)),
                ('consented_at', models.DateTimeField(auto_now_add=True)),
                ('withdrawn_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AssessmentResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_key', models.CharField(max_length=100)),
                ('answer_value', models.CharField(max_length=200)),
                ('answer_label', models.CharField(blank=True, max_length=500)),
                ('response_order', models.IntegerField(default=0)),
                ('responded_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='api.assessmentsession')),
            ],
        ),
        migrations.AddField(
            model_name='assessmentsession',
            name='participant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='api.researchconsent'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('student', 'Student'), ('faculty', 'Faculty'), ('admin', 'Admin')], max_length=20)),
                ('department', models.CharField(blank=True, max_length=100)),
                ('years_in_academia', models.IntegerField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
