# Generated by Django 6.0.1 on 2026-04-01 20:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_checkpoint_project_decision_checkpoint_project'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='checkpoint',
            name='frameworks',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('faculty', 'Faculty')], max_length=20),
        ),
        migrations.CreateModel(
            name='AITool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('vendor', models.CharField(blank=True, max_length=200)),
                ('category', models.CharField(choices=[('chatbot', 'Chatbot'), ('code_assistant', 'Code Assistant'), ('grading', 'Grading'), ('writing', 'Writing'), ('image_gen', 'Image Generation'), ('data_analysis', 'Data Analysis'), ('research', 'Research'), ('other', 'Other')], max_length=30)),
                ('status', models.CharField(choices=[('approved', 'Approved'), ('under_review', 'Under Review'), ('not_recommended', 'Not Recommended')], default='under_review', max_length=20)),
                ('risk_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_tools', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='project',
            name='ai_tools',
            field=models.ManyToManyField(blank=True, related_name='projects', to='api.aitool'),
        ),
        migrations.CreateModel(
            name='CheckpointComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('checkpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='api.checkpoint')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkpoint_comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
