# Generated by Django 6.0.1 on 2026-04-07 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_checkpoint_frameworks_alter_userprofile_role_aitool_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aitool',
            name='compliance_guidance',
            field=models.JSONField(blank=True, default=dict, help_text='How to use this tool compliantly for each use case'),
        ),
        migrations.AddField(
            model_name='aitool',
            name='data_retention_details',
            field=models.TextField(blank=True, help_text='How long is data retained and where?'),
        ),
        migrations.AddField(
            model_name='aitool',
            name='ferpa_compliant',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='aitool',
            name='has_enterprise_plan',
            field=models.BooleanField(default=False, help_text='Does it offer an institutional plan with better data controls?'),
        ),
        migrations.AddField(
            model_name='aitool',
            name='hipaa_compliant',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='aitool',
            name='recommended_use_cases',
            field=models.JSONField(blank=True, default=list, help_text='List of use case keys this tool is suitable for'),
        ),
        migrations.AddField(
            model_name='aitool',
            name='retains_data',
            field=models.BooleanField(default=True, help_text='Does the tool retain user data?'),
        ),
        migrations.AddField(
            model_name='aitool',
            name='sends_to_third_party',
            field=models.BooleanField(default=True, help_text='Does data leave the institution?'),
        ),
    ]
