# Generated by Django 5.2.5 on 2026-04-08 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_aitool_compliance_guidance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aitool',
            name='tool_type',
            field=models.CharField(choices=[('ai', 'AI Tool'), ('general', 'Productivity & Research')], default='ai', max_length=10),
        ),
        migrations.AddField(
            model_name='aitool',
            name='website_url',
            field=models.URLField(blank=True, help_text='Link to the tool website'),
        ),
        migrations.AlterField(
            model_name='aitool',
            name='category',
            field=models.CharField(choices=[('chatbot', 'Chatbot'), ('code_assistant', 'Code Assistant'), ('grading', 'Grading'), ('writing', 'Writing'), ('image_gen', 'Image Generation'), ('data_analysis', 'Data Analysis'), ('research', 'Research'), ('survey', 'Survey & Forms'), ('statistics', 'Statistics'), ('qualitative', 'Qualitative Analysis'), ('reference', 'Reference Management'), ('collaboration', 'Collaboration'), ('lms', 'Learning Management'), ('visualization', 'Data Visualization'), ('other', 'Other')], max_length=30),
        ),
        migrations.AlterField(
            model_name='aitool',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='assessmentresponse',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='assessmentsession',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='checkpoint',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='checkpointcomment',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='decision',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='project',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='researchconsent',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
