# Generated by Django 5.2.5 on 2026-04-08 20:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_add_tool_type_and_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='decision',
            name='tool_used',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decisions', to='api.aitool'),
        ),
    ]
