# Generated by Django 6.0.1 on 2026-04-10 12:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_add_faculty_advisor_to_project'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='student_collaborator',
            field=models.ForeignKey(blank=True, help_text='Student who shares access to this activity', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collaborated_projects', to=settings.AUTH_USER_MODEL),
        ),
    ]
